version: '3.4'

services:
  jaeger:
    image: jaegertracing/all-in-one
    
  reportmanagement:
    image: ${DOCKER_REGISTRY-}reportmanagementapi
    build:
      context: .
      dockerfile: src/ReportManagement.API/Dockerfile
    environment:
      Mongo__ConnectionString: "mongodb://root:rootpassword@localhost:27017"
      Mongo__DatabaseName: "testdb"
    


  